on:
  workflow_dispatch:

jobs:

  job1_satyam:
    name: run to Ubuntu
    runs-on: ubuntu-22.04
    steps:
       
      - name: Checkout Step
        uses: actions/checkout@v4.0.0
      
      - name: welcome gretting
        run: |
         pwd
         whoami
         ls
         nano abc.txt
   

  
 


